#!/usr/bin/expect -f 

set force_conservative 1; 
set timeout -1
set cmd1 [lindex $argv 0]
set cmd2 [lindex $argv 1]

spawn ./ev3-connect $cmd1 $cmd2

expect {
Password: {
send "maker\r";
#exp_continue
interact
}
}


