#! /bin/bash

#Se connecter une première fois avec ssh robot@[IP] pour enregistrer le mot de passe de la connexion ssh.
#EV3 CHO
IPUSB="10.42.0.71" #USB LINUX
#IPUSB="169.254.230.22" #USB LINUX
#IPWIFI="192.168.2.102" #WIFI anciennce clef wifi
IPWIFI="192.168.2.104"
#IPHOME="192.168.0.217" #WIFI HOME CHO INDEED2G
IPHOME="192.168.0.220" #WIFI HOME CHO INDEED

#EV3 ChristopheD
#IPWIFI="192.168.2.102" #WIFI



all()
{
	scp "../Bot_LegoMindstorm_EV3/Release/Bot_LegoMindstorm_EV3" "../Driver-EV3-UnitTest/Debug/Driver-EV3-UnitTest" robot@$IP:/home/robot/pmx
}

main()
{

	ssh robot@$IP "killall Bot_LegoMindstorm_EV3";
	scp "../Bot_LegoMindstorm_EV3/Release/Bot_LegoMindstorm_EV3" "../src/Bot-LegoEV3/config_LegoEV3Robot.txt" robot@$IP:/home/robot/pmx
}

driver()
{
	
	scp "../Driver-UnitTest_EV3/Debug/Driver-UnitTest_EV3" robot@$IP:/home/robot/pmx	
	
}

tests()
{
	scp "../../ev3dev-lang-cpp/build/tests/api_tests" "../../ev3dev-lang-cpp/build/demos/button-test"  "../../ev3dev-lang-cpp/build/demos/ev3dev-lang-demo" "../../ev3dev-lang-cpp/build/demos/ev3dev-lang-test" "../../ev3dev-lang-cpp/build/demos/sound-test" robot@$IP:/home/robot/pmx	
	
}

recup()
{
#faire un repertoire de logs
        #scp "robot@$IP:/home/robot/pmx/*.csv /home/robot/pmx/*.svg" /home/pmx/recup
        #scp "robot@$IP:/home/robot/pmx/logAsserv.csv /home/robot/pmx/logRegul.csv /home/robot/pmx/svgEV3.svg /home/robot/pmx/svgIA.svg" /home/pmx/recup
        scp "robot@$IP:/home/robot/pmx/*.csv" /home/pmx/recup
        scp "robot@$IP:/home/robot/pmx/*.svg" /home/pmx/recup
        
}

connect()
{
	ssh robot@$IP
}

case "$1" in
	usb)
		IP=$IPUSB
	;;
	wifi)
		IP=$IPWIFI
	;;
	
	home)
		IP=$IPHOME
	;;
	
	*)
		IP=$IPUSB
	;;
esac

case "$2" in
	view-doc)
		view_doc;;
	connect)
		connect;;
	all)
		all;;
	driver)
		driver;;
	main)
		main;;
	recup)
		recup;;
	tests)
		tests;;

	*)
		echo "Usage: $0 {usb|wifi|home} {connect|all|main|driver|tests}" >&2
		exit 1
	;;
esac

exit 0
