#! /bin/bash

#Se connecter une première fois avec ssh robot@[IP] pour enregistrer le mot de passe de la connexion ssh.
#EV3 CHO
IPUSB="10.42.0.71" #USB LINUX
IPWIFI="192.168.2.102" #WIFI
IPHOME="192.168.0.212" #WIFI HOME CHO

#EV3 ChristopheD
#IPWIFI="192.168.2.102" #WIFI



all()
{
    #ssh root@$IP "killall Bot-SmallPMX-EV3"
	scp "../Bot_LegoMindstorm_EV3/Release/Bot_LegoMindstorm_EV3" "../Driver-EV3-UnitTest/Debug/Driver-EV3-UnitTest" robot@$IP:/home/robot/
	
}

main()
{
	scp "../Bot_LegoMindstorm_EV3/Release/Bot_LegoMindstorm_EV3" robot@$IP:/home/robot/	
}

driver()
{
	scp "../Driver-UnitTest_EV3/Debug/Driver-UnitTest_EV3" robot@$IP:/home/robot/	
	
}

tests()
{
	scp "../../ev3dev-lang-cpp/build/tests/api_tests" "../../ev3dev-lang-cpp/build/demos/button-test"  "../../ev3dev-lang-cpp/build/demos/ev3dev-lang-demo" "../../ev3dev-lang-cpp/build/demos/ev3dev-lang-test" "../../ev3dev-lang-cpp/build/demos/sound-test" robot@$IP:/home/robot/	
	
}

recup()
{
        scp "robot@$IP:/home/robot/*.csv /home/robot/*.svg" /home/pmx/recup/.
}

connect()
{
	ssh robot@$IP
}

case "$1" in
	usb)
		IP=$IPUSB
	;;
	wifi)
		IP=$IPWIFI
	;;
	
	home)
		IP=$IPHOME
	;;
	
	*)
		IP=$IPUSB
	;;
esac

case "$2" in
	view-doc)
		view_doc;;
	connect)
		connect;;
	all)
		all;;
	driver)
		driver;;
	main)
		main;;
	recup)
		recup;;
	tests)
		tests;;

	*)
		echo "Usage: $0 {usb|wifi|home} {connect|all|main|driver|tests|recup|view-doc}" >&2
		exit 1
	;;
esac

exit 0
