#! /bin/bash

#Se connecter une première fois avec ssh robot@[IP] pour enregistrer le mot de passe de la connexion ssh.

IPHOME="192.168.0.212" #WIFI HOME CHO
IPWIFI="192.168.2.107" #WIFI PMX
IPETH0="192.168.2.105" #ETH0 PMX

view_doc()
{
    firefox doc/html/index.html >/dev/null 2>&1 &
}

all()
{
	scp "../Bot_ArmadeusOPOS6UL_ARM/Release/Bot_ArmadeusOPOS6UL_ARM" "../Driver-UnitTest_OPOS6UL_ARM/Debug/Driver-UnitTest_OPOS6UL_ARM" "../Common-UnitTest_OPOS6UL_ARM/Debug/Common-UnitTest_OPOS6UL_ARM" root@$IP:/root/.
}

tsh()
{
	scp ../sh/*.sh root@$IP:/root/
}

kill()
{
    ssh root@$IP "killall Bot_ArmadeusOPOS6UL_ARM"
}

main()
{
    ssh root@$IP "killall Bot_ArmadeusOPOS6UL_ARM"
	scp "../Bot_ArmadeusOPOS6UL_ARM/Release/Bot_ArmadeusOPOS6UL_ARM" root@$IP:/root/.
}

driver()
{
	scp "../Driver-UnitTest_OPOS6UL_ARM/Debug/Driver-UnitTest_OPOS6UL_ARM" root@$IP:/root/.
}

common()
{
	scp "../Common-UnitTest_OPOS6UL_ARM/Debug/Common-UnitTest_OPOS6UL_ARM" root@$IP:/root/.
}

recupcsvhost()
{
    #recup sur le PC Host
	scp root@$IP:/root/*.* /mnt/hgfs/pmx_xls/.
}

recupcsv()
{
        scp root@$IP:/root/*.csv /home/pmx/recup/.
}

recupsvg()
{
        scp root@$IP:/root/*.svg /home/pmx/recup/.
}

connect()
{
	ssh root@$IP
}


case "$1" in
	eth0)
		IP=$IPETH0
	;;
	wifi)
		IP=$IPWIFI
	;;
	
	home)
		IP=$IPHOME
	;;
	
	*)
		IP=$IPETH0
	;;
esac

case "$2" in
	view-doc)
		view_doc
	;;

	all)
		all
	;;

	tsh)
		tsh
	;;

	main)
		main
	;;

	kill)
		kill
	;;

	driver)
		driver
	;;

	common)
		common
	;;

	connect)
		connect
	;;
        
        recupcsv)
		recupcsv
	;;

        recupsvg)
		recupsvg
	;;

        recupcsvhost)
		recupcsvhost
	;;

	*)
		echo "Usage: $0 {eth0|wifi|home} {connect|main|kill|common|driver|all|tsh|view-doc|recupcsv|recupsvg|recupcsvhost}" >&2
		exit 1
	;;
esac

exit 0
