#! /bin/bash

#Se connecter une première fois avec ssh robot@[IP] pour enregistrer le mot de passe de la connexion ssh.

IP="192.168.2.150" #RJ45

view_doc()
{
    firefox doc/html/index.html >/dev/null 2>&1 &
}

all()
{
	scp "../Bot_ArmadeusAPF9328_ARM/Release/Bot_ArmadeusAPF9328_ARM" "../Driver-ARM-UnitTest/Debug/Driver-ARM-UnitTest" root@$IP:/root/.
}

conf()
{
	scp "../Bot_ArmadeusAPF9328_ARM/Release/*.conf.txt" root@$IP:/pmx/
}

tsh()
{
	scp ../sh/*.sh root@$IP:/pmx/
}


pmx()
{
    #ssh root@$IP "killall pmx"
	scp "../Bot_ArmadeusAPF9328_ARM/Release/Bot_ArmadeusAPF9328_ARM" root@$IP:/root/.
}

driver()
{
	scp "../Driver-ARM-UnitTest/Debug/Driver-ARM-UnitTest" root@$IP:/root/.
}


recupcsvhost()
{
    #recup sur le PC Host
	scp root@$IP:/pmx/*.* /mnt/hgfs/pmx_xls/
}

recupcsv()
{
        scp root@$IP:/pmx/*.* /home/pmx/Arecup/.
}

recupsvg()
{
        scp root@$IP:/pmx/*.svg /home/pmx/workspace/ARM/SVG/.
}

connect()
{
	ssh root@$IP
}

case "$1" in
	view-doc)
		view_doc
	;;

	all)
		all
	;;

	conf)
		conf
	;;

	tsh)
		tsh
	;;

	pmx)
		pmx
	;;

	driver)
		driver
	;;

	connect)
		connect
	;;
        
        recupcsv)
		recupcsv
	;;

        recupsvg)
		recupsvg
	;;

        recupcsvhost)
		recupcsvhost
	;;

	*)
		echo "Usage: $0 {connect|pmx|driver|all|conf|tsh|view-doc|recupcsv|recupsvg|recupcsvhost}" >&2
		exit 1
	;;
esac

exit 0
